version: 2.1
orbs:
  checkov: bridgecrew/checkov@0.0.4
jobs:
  build:
    machine: true
    steps:
      - checkov/scan:
          api-key: 
          directory: ./MREPO1
          file: 
          output: json
          repo-id: 
          soft-fail: false